apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  namespace: final
  labels:
    app: django
spec:
  selector:
    matchLabels:
      app: django
      tier: backend
  template:
    metadata:
      labels:
        app: django
        tier: backend
    spec:
      containers:
      # - name: nginx
      #   image: nginx:latest
      - name: django
        image: 767397926607.dkr.ecr.ap-northeast-2.amazonaws.com/umatter:latest
        envFrom:
        - configMapRef:
            name: django-config
        ports:
        - name: gunicorn
          containerPort: 8000
        #   requests:
        #     cpu: 100m
        #     memory: 500Mi
        #   limits:
        #     cpu: 200m
        #     memory: 1Gi
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 80
        #     httpHeaders:
        #     - name: Custom-Header
        #       value: Awesome
        #   initialDelaySeconds: 3
        #   periodSeconds: 3