apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  namespace: final
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
      tier: backend
  template:
    metadata:
      labels:
        app: django
        tier: backend
    spec:
      containers:
      - name: django
        image: 767397926607.dkr.ecr.ap-northeast-2.amazonaws.com/umatter:latest
        envFrom:
        - configMapRef:
            name: django-config
        ports:
        - name: gunicorn
          containerPort: 8000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 5
        resources:
          requests:
            cpu: 600m
            memory: 500Mi
          limits:
            cpu: 900m
            memory: 1Gi