apiVersion: v1
kind: Service
metadata:
  name: django
  namespace: final
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/"
  labels:
    app: django
spec:
  ports:
    - port: 80
  selector:
    app: django
    tier: backend
  type: LoadBalancer